language: rust

cache:
  apt: true
  directories:
    - $TRAVIS_HOME/.cargo/
    - $TRAVIS_HOME/.cache/sccache

before_cache:
  - rm -rf "$TRAVIS_HOME"/.cargo/registry"

script:
  - travis_wait 30 cargo build --verbose --all
  - cargo test --verbose --all --all-features
