[workspace]
members = [
	"bin/main",
	"bin/main/init",
	"bin/main/node",
	"core/crypto",
	"core/crypto/dylib-samples/hash",
	"core/primitives",
	"core/node/db",
	"core/node/statedb",
	"core/node/service",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
