[workspace]
members = [
	"bin/main",
	"bin/main/init",
	"bin/main/node",
	"utils/test",
	"utils/hash_enum",
	"utils/hash_enum_derive",
	"core/crypto",
	"core/crypto/dylib-samples/hash",
	"core/crypto/dylib-samples/dsa",
	"core/crypto/dylib-samples/address",
	"core/primitives",
	"core/node/db",
	"core/node/statedb",
	"core/node/service",
	"core/node/executor",
	"core/node/executor/primitives",
	"core/node/txpool",
	"core/module/system",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
