[package]
name = "node-executor-primitives"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-codec = { version = "4.1.4", features = ["derive"] }

node-db = { path = "../../db" }
primitives = { path = "../../../primitives" }
