[package]
name = "main-init"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"
error-chain = "0.12.2"
rand = "0.7.3"
chrono = "0.4.11"
toml = "0.5.6"

base = { package = "main-base", path = "../base" }

[dev-dependencies]
assert_cmd = "0.12.0"
tempfile = "3.1.0"
serde = "1.0"
serde_json = "1.0"

[features]
build-dep-test = []
