# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[txpool]
pool_capacity = 102040
buffer_capacity = 10240

[api]
rpc_addr = "0.0.0.0:3109"
rpc_workers = 0
rpc_maxconn = 10240

[validator]
secret_key_file = "secret_key.dat"

[network]
max_in_peers = 32
max_out_peers = 32
listen_addresses = [ "0.0.0.0:3110" ]
external_addresses = []
# libp2p multaddr, e.g. /ip4/127.0.0.1/tcp/3110/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN
bootnodes = []
# libp2p multaddr, e.g. /ip4/127.0.0.1/tcp/3110/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN
reserved_nodes = []
reserved_only = false
secret_key_file = "network_secret_key.dat"
