# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTICE: This file should NOT be modified once the chain node is started.

[genesis]

# Set an unique chain id
[[genesis.txs]]
method = "system.set_chain_id"
params = ["${CHAIN_ID}"]

# Set genesis block time
[[genesis.txs]]
method = "system.set_time"
params = [${TIME}]
