# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTICE: This file should NOT be modified once the chain node is started.

[basic]
hash = "blake2b_256"
dsa = "ed25519"
address = "blake2b_160"

[genesis]

[[genesis.txs]]
module = "system"
method = "init"
params = '''
{
    "chain_id": "${CHAIN_ID}",
    "timestamp": "${TIME}",
    "until_gap": 20
}
'''

[[genesis.txs]]
module = "balance"
method = "init"
params = '''
{
    "endow": []
}
'''

[[genesis.txs]]
module = "poa"
method = "init"
params = '''
{
    "block_interval": 3000
}
'''

[[genesis.txs]]
module = "contract"
method = "init"
params = '''
{
}
'''
