# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTICE: This file should NOT be modified once the chain node is started.

[genesis]

# System module init
[[genesis.txs]]
method = "system.init"
params = ['''
{
    "chain_id": "${CHAIN_ID}",
    "time": "${TIME}",
    "hash": "blake2b_256",
    "dsa": "ed25519",
    "address": "blake2b_160"
}
''']
