[package]
name = "node-txpool"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chashmap = "2.2.2"
tokio ={ version = "0.2.17", features = ["rt-core", "time", "sync", "stream", "macros"] }
parking_lot = "0.10"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.8"

primitives = { path = "../../primitives" }
node-chain = { path = "../chain" }

[dev-dependencies]
crypto = { path = "../../crypto" }
rand = "0.4.6"
futures = "0.3"
