[package]
name = "main-node"
version = "0.1.0"
authors = ["developer <developer@wingchain.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"
error-chain = "0.12.2"

base = { package = "main-base", path = "../base" }
